# This is a basic workflow to help you get started with Actions

name: Generate

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: bjerkio/swagger-codegen-action@master
      name: Generate with Swagger
      with:
        args: generate -i https://pennydreadfulmagic.com/api/swagger.json -l csharp --config config.json
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.8.0
      with:
        commit-message: Updated swagger
        title: Update
        branch: update
        labels: merge when ready
